channels:
  - moble
  - defaults
dependencies:
  - ca-certificates=2017.08.26
  - certifi=2018.1.18
  - cycler=0.10.0
  - dbus=1.12.2
  - expat=2.2.5
  - fontconfig=2.12.6
  - freetype=2.8
  - glib=2.53.6
  - gst-plugins-base=1.12.4
  - gstreamer=1.12.4
  - icu=58.2
  - intel-openmp=2018.0.0
  - jpeg=9b
  - kiwisolver=1.0.1
  - libedit=3.1
  - libffi=3.2.1
  - libgcc-ng=7.2.0
  - libgfortran-ng=7.2.0
  - libpng=1.6.34
  - libstdcxx-ng=7.2.0
  - libxcb=1.12
  - libxml2=2.9.7
  - llvmlite=0.22.0
  - matplotlib=2.1.0
  - mkl=2018.0.1
  - ncurses=6.0
  - numba=0.37.0
  - numpy=1.14.1
  - openssl=1.0.2n
  - pandas=0.22.0
  - pcre=8.41
  - pip=9.0.1
  - pyparsing=2.2.0
  - pyqt=5.6.0
  - python=3.6.4
  - python-dateutil=2.7.0
  - pytz=2018.3
  - qt=5.6.2
  - readline=7.0
  - scipy=1.0.0
  - setuptools=38.5.1
  - sip=4.18.1
  - six=1.11.0
  - sqlite=3.22.0
  - tk=8.6.7
  - tornado=5.0
  - wheel=0.30.0
  - xz=5.2.3
  - zlib=1.2.11
  - quaternion=2018.03.06.20.03.47
  - pip:
    - numpy-quaternion==2018.3.7.1.23.24
